### ISSUE TITLE
Release 0.7.4 to clojars?

### ISSUE THREAD

**Issue by MikaelSmith** [ngrunwald/datasplash#109]
How long does it usually take for a release to show up on clojars?

**Comment by edporras** [comment]
As far as I know, @ngrunwald is the only one who can deploy 😞

**Comment by MikaelSmith** [comment]
Any suggestions on pulling this in directly rather than via Clojars?

**Comment by edporras** [comment]
@MikaelSmith @domparry 0.7.4 is now available on clojars.
