### ISSUE TITLE
swap out cheshire for jsonista

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#110]
I'm considering swapping out cheshire for jsonista (https://github.com/metosin/jsonista). It offers significantly faster parsing to and from json, and still uses jackson under the covers.

Would there be any objections? I'm keen to do this on our fork, but don't want to diverge too much from datasplash.

**Comment by ngrunwald** [comment]
No objection at all from me at least, PR welcome :)

**Comment by domparry** [comment]
Great! Thanks. I'll send a PR once I have tested thoroughly here.

**Comment by domparry** [comment]
Murphey's Law... I push and start to prepare the MR, and this get's published: https://cnuernber.github.io/dtype-next/tech.v3.datatype.char-input.html#var-read-json

It's the speed of jsonista, but WITHOUT the need for jackson dependancy.... I need to investigate some more though, but it looks like a great option.

**Comment by domparry** [comment]
I have been running the jsonista version in prod all day on batch and streaming pipeines, but only for pubsub -> bigquery, datastore -> bigQuery, and datastore -> datastore. I'm happy that it's working well.

I'll submit the MR with this version now. If I find the energy, I'll look at moving to the lib above to remove the dependency on jackson.
