### ISSUE TITLE
Library size and AOT compilation

### ISSUE THREAD

**Issue by kawas44** [ngrunwald/datasplash#146]
Hello,

As of the latest Datasplash version (0.7.16), the jar size is 3.3 Mb.

This size is mainly due to AOT compilation of few classes pulled by the project `:main` entry. This main entry is just to run code exemples and we already describe in the README how to run them from the repl.

So, we could remove the project `:main` entry definition and avoid any AOT compilation, which will have the effect of reducing the jar size to only a few Kb (~67 Kb).

If I understand correctly, Datasplash needs to be AOT compiled *only* in our users' projects, but the lib itself does not need it, right?

**Comment by edporras** [comment]
This sounds great to me.
