### ISSUE TITLE
Apache Beam support

### ISSUE THREAD

**Issue by atroche** [ngrunwald/datasplash#16]
Hey guys,

Just ran my first job on Dataflow using datasplash today, and it worked great. Thanks for the library!

Any plans to migrate to Beam? Any idea how big a change it would be to datasplash?

Cheers!

**Comment by atroche** [comment]
FWIW I tried running https://github.com/teddziuba/beam-clj on Dataflow and ran into critical problems with unbound function exceptions

**Comment by dspiteself** [comment]
@atroche do you still have the same problems [here](https://github.com/dspiteself/beam-clj)

**Comment by domparry** [comment]
This would be amazing. I'm not really at the level of being able to contribute meaningfully, but would certainly throw plenty of "try" at it. For example, the new dataflow Templates need an API version bump to > 2.0 in order to execute templates including BQ jobs more than once.

**Comment by domparry** [comment]
Hi All,

I have started to try and port this to 2.0, and committed where I am at the moment to here: https://github.com/SimplyFinServices/datasplash Although I'm able to compile the project now, there are still some run time things that need to be solved (See the failing tests). I'm getting to the limits of my knowledge here, and any help / pointers would be appreciated....

**Comment by m-lce** [comment]
Hi, We have WIP in branch v2. The core features should be ok. Feel free to test and report any issues you could find.

**Comment by dspiteself** [comment]
One note. You would not need 'safe-exec' and company it your required the namespace from ClojureDoFn.  I know there are a lot of trade offs but I would love to talk through them.

**Comment by domparry** [comment]
This is great @m-lce . Thanks to you guys. I gave migrating it myself an initial try but ran out of know-how pretty fast....

**Comment by torbjornvatn** [comment]
I also got a bit down that path, with pretty much the same approach as you @m-lce, but ran into some very low level Java compiler issues. Great that you have started on this, as it's quite crucial for a talk I'm giving at [JavaZone](https://2017.javazone.no/program/d66babf3b55e440aab52ea06958d136f) in about a month

**Comment by m-lce** [comment]
done in 0.5.0
