### ISSUE TITLE
Documents at http://theblankscreen.net/datasplash/index.html show incorrect installation instructions

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#18]
I'm assuming what's happened is merging the branch from uncast still reference 0.4.2-SNAPSHOT, because the instructions state to add:

`[datasplash "0.4.2-SNAPSHOT"]`

**Comment by torbjornvatn** [comment]
Bump, the docs should be updated to 0.5.0, maybe including my PR #34 to reflect the change in the  signature of `get-pipeline-configuration`

**Comment by bfontaine** [comment]
Should be fixed once the website is back online (#37).

**Comment by bfontaine** [comment]
It’s up-to-date on the new URL: https://oscaro.github.io/datasplash/
