### ISSUE TITLE
Read from PubSub topic #10 seems to be a breaking change.

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#19]
I get the following compilation error now when switching to the new version:

`Exception in thread "main" clojure.lang.ExceptionInfo: Wrong type of :kind for pubsub [null], should be either :subscription or :topic {:kind nil},`

Oddly, using Uncast version 0.4.2 (where I think this code comes from, it works just fine. I'm invoking the call like this:

```
 (->> pipeline

      (ps/read-from-pubsub read-subscription {:name "Read events from pubsub"}))
```

**Comment by torbjornvatn** [comment]
Indeed it is a bug there @domparry, I hope to have fixed it with https://github.com/ngrunwald/datasplash/pull/20

**Comment by ngrunwald** [comment]
This seems to be indeed fixed, thanks!
