### ISSUE TITLE
Is this lib production ready ?

### ISSUE THREAD

**Issue by rhacker** [ngrunwald/datasplash#2]
Thanks for creating the lib. I wonder is this one production ready, I can see that the deps are a bit outdated.

**Comment by ngrunwald** [comment]
Sorry I missed your question, this lib has been used daily in production at _Oscaro.com_ for 18 months on datasets over 30 To. There are still some unfortunate rough edges around error reporting and wrapping the streaming mode, but it's definitely production ready :) Don't hesitate to ask if you encounter problems :)
