### ISSUE TITLE
populateDisplayData in datasplash v2 

### ISSUE THREAD

**Issue by dspiteself** [ngrunwald/datasplash#24]
It would be great to implement [populateDisplayData](https://beam.apache.org/documentation/sdks/javadoc/0.5.0/org/apache/beam/sdk/transforms/DoFn.html#populateDisplayData-org.apache.beam.sdk.transforms.display.DisplayData.Builder-) on ClojureDoFN. I we do it right we could display more clojure context information from dataflows gui.

**Comment by bfontaine** [comment]
I’m closing this for now, but pull-requests are welcome! :slightly_smiling_face:
