### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by MartinSahlen** [ngrunwald/datasplash#4]
Are you able to release the current version on the github master? We are working with a project that needs to use side-outputs. Currently we can manage by pulling the repo as a git dependency but it would be nice to have it on clojars. We would also be happy to contribute in the future. 

Best, Martin / Unacast

**Comment by ngrunwald** [comment]
Sorry to have missed your issue, I'll be doing a release very shortly, we've been using master for some time now in production and it seems quite safe :) Glad to take any contribution !

**Comment by ngrunwald** [comment]
Version 0.3.0 released on clojars :)
