### ISSUE TITLE
Error: `java.lang.IllegalArgumentException: unable to deserialize datasplash.fns.ClojureDoFn`

### ISSUE THREAD

**Issue by jasonmm** [ngrunwald/datasplash#46]
I want to window some data that does not have a timestamp. I'm trying to follow [this example code](https://github.com/apache/beam/blob/d314339ed2f8d5ce385c7b40705ef13f6ea43b45/examples/java/src/main/java/org/apache/beam/examples/WindowedWordCount.java) to add a timestamp to that data.  I believe I need to use [`pardo`](https://oscaro.github.io/datasplash/datasplash.api.html#var-pardo) to accomplish this.  However, I am getting the following error:

    Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize datasplash.fns.ClojureDoFn@34bddf43
    [..snip..]
    Caused by: java.lang.ClassNotFoundException: dataflow_test.core$add_timestamp

The code is:

```clojure
(defn add-timestamp
  [ctx]
  (pp/pprint (type ctx)))

(defn -main
  [& args]
  (let [pipeline (ds/make-pipeline DataflowPipelineOptions [] pipeline-options)]
    (->> pipeline
         (ds/read-text-file (env :input-filename) {:name "read-file"})
         (ds/pardo add-timestamp {:name "add-timestamp"})
         (ds/write-json-file (env :output-filename) {:name       "write-file"
                                                     :num-shards 1
                                                     :suffix     ".json"}))))
```

What is the proper way to use `pardo`? Or, is there a better way to add a new field to data?

**Comment by RolT** [comment]
I don't know the proper way to use pardo, but if you do not need the context to set the timestamp but just the element you can simply use a `map` operation. See [this example](https://oscaro.github.io/datasplash/datasplash.api.html#var-with-timestamp).

**Comment by jasonmm** [comment]
I essentially still receive the same error, just with a different `ClassNotFoundException`:

    Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize datasplash.fns.ClojureDoFn@160546b1
    [..snip..]
    Caused by: java.lang.ClassNotFoundException: dataflow_test.core$_main$fn__865

Here's the new `-main`:

```clojure
(defn -main
  [& args]
  (let [pipeline (ds/make-pipeline DataflowPipelineOptions [] pipeline-options)]
    (->> pipeline
         (ds/read-text-file (env :input-filename) {:name "read-file"})
         (ds/map (fn [e] (ds/with-timestamp (clj-time.core/now) e)))  ;; <-- this line changed
         (ds/write-json-file (env :output-filename) {:name       "write-file"
                                                     :num-shards 1
                                                     :suffix     ".json"}))))
```

I'm not sure what `e` is supposed to be. Looking at the examples in the Datasplash docs it would appear to be a number since multiplication is applied to it.

**Comment by RolT** [comment]
Functions used in the pipeline need to be compiled, I think we make this clear in the readme. If you're running with an uberjar, make sure you don't have `:skip-aot dataflow_test.core` in your `project.clj`. If you are running it from the repl or with `lein run`, you should move the anonymous function to a named one and add `('compile dataflow_test.core)` in your `-main` like [this](https://github.com/ngrunwald/datasplash/blob/master/src/clj/datasplash/examples.clj#L338).

Here `e` refer to an element of the PCollection. With `pardo` you get the whole context object but I've never used it.

**Comment by jasonmm** [comment]
I don't see AOT or compiling mentioned in the README, but your explanation is very clear.  After following your instructions the error no longer occurs.  However, the output file does not contain the timestamp that I thought was being added to each record.

**Comment by jasonmm** [comment]
After some more investigation I was able to get the timestamp to appear in the output by manipulating the [`TimeStamped` record](https://github.com/ngrunwald/datasplash/blob/v0.5.3/src/clj/datasplash/core.clj#L267) returned from [`with-timestamp`](https://github.com/ngrunwald/datasplash/blob/v0.5.3/src/clj/datasplash/core.clj#L269). Allowing the return of `with-timestamp` to be returned directly from the mapping function did not work. Possibly something to do with lazy sequences?

As an example, the following code snippet works. For each line in the input file the following code will output a string representation of a vector with 2 elements: a string timestamp, and a line from the input file.

```clojure
(defn add-timestamp
  [pcoll]
  (let [time-stamped (ds/with-timestamp (clj-time.core/now) pcoll)]
    [(->> time-stamped :timestamp format-ts) (:result time-stamped)]))

(defn stringify [pcoll] (str pcoll))

(defn -main
  [& args]
  (compile 'dataflow-test.core)
  (let [pipeline (ds/make-pipeline DataflowPipelineOptions [] pipeline-options)]
    (->> pipeline
         (ds/read-text-file (env :input-filename) {:name "read-file"})
         (ds/map add-timestamp)
         (ds/map stringify)
         (ds/write-text-file (env :output-filename) {:name "write-file" :num-shards 1 :suffix ".csv"}))
    (ds/run-pipeline pipeline)))
```

Am I understanding how to use `with-timestamp` correctly?

**Comment by RolT** [comment]
It depends on what you are trying to do.

If you just want to write timestamps then `ds/with-timestamp` is unnecessary. Just modify the elements with `ds/map`.

If you want the timestamps to be taken in account in dataflow windows, then you should use `ds/with-timestamp` as in the example. They will be added to the context object, not the element, so they won't be written with `ds/write-text-file`. You should still be able to access them with `ds/pardo` I guess.

**Comment by jasonmm** [comment]
> They [timestamps] will be added to the context object, not the element

That was the part I was missing. Thank you for explaining that.
