### ISSUE TITLE
`sliding-windows` vs `SlidingWindows`

### ISSUE THREAD

**Issue by jasonmm** [ngrunwald/datasplash#50]
The sliding windows in [this Java code](https://gist.github.com/jasonmm/fe32579a475101484dc4488b11e01283#file-file-java) work as I would expect them to. Each window is one file that contains the elements from that window.

The sliding windows in [this Clojure code](https://gist.github.com/jasonmm/fe32579a475101484dc4488b11e01283#file-core-clj) behave differently. Each window is split across multiple files with each file containing a portion of the elements from that window.

The two pipelines are intended to behave identically, and, with the exception of the output files, do appear to behave identically.

Reading the code for `sliding-windows` I can't see what would cause the difference. Is `sliding-windows` intended to behave differently from `SlidingWindows`?  If so, what is the proper way to duplicate the functionality of `SlidingWindows`?

**Comment by RolT** [comment]
Hi, the difference I see is the use of `withWindowedWrites()` in the java code. This is not available in datasplash. Maybe you can use [ds/filename-policy](https://oscaro.github.io/datasplash/datasplash.api.html#var-filename-policy). Or modify [ds/wirte-text-file](https://github.com/ngrunwald/datasplash/blob/v0.5.2/src/clj/datasplash/core.clj#L1112).

**Comment by jasonmm** [comment]
Reading [this line](https://github.com/ngrunwald/datasplash/blob/v0.5.3/src/clj/datasplash/core.clj#L1092), it looks like `:windowed true` causes `withWindowedWrites()` to be called. Am I not reading the code correctly?

**Comment by RolT** [comment]
My bad I didnt read correctly. I have no idea what's causing the difference then.

**Comment by jasonmm** [comment]
The difference appears to be caused by `write-text-file`, not `sliding-windows` as I first suspected.

Replacing `write-text-file` in my pipeline with calls directly to the Java functions, as in the following code snippet, does write one file per window.

```clojure
(defn output
  [pipeline]
  (.apply pipeline (.. (TextIO/write)
                       (to "output/output")
                       (withWindowedWrites)
                       (withNumShards 1))))

(defn -main
  [& args]
  (compile '<current-namespace>)
  (->> (ds/make-pipeline [])
       (ds/read-text-file "input.txt" {:name :read-input})
       (ds/map-kv (fn [e] [e (-> e first int)]) {:name :number-words})
       (ds/map (fn [e] (ds/with-timestamp (clj-time.coerce/from-long (* 1000 (second e))) e)) {:name :timestamp})
       (ds/sliding-windows (clj-time.core/seconds 10) (clj-time.core/seconds 1) {:name :sliding})
       (ds/map (fn [e] (str (first e) ":" (second e))))
       (output)  ;; <-- used to be `write-text-file`
       ds/run-pipeline))
```

**Comment by RolT** [comment]
Can you try `(ds/write-text-file "output/output" {:name :write :num-shards 1 :windowed true})` ?
You were using `numShards` in your code.

**Comment by jasonmm** [comment]
Thank you!  That was it.  It just didn't make any sense, but now it does.
