### ISSUE TITLE
Examples (including README) are outdated, will not run on GCP Dataflow

### ISSUE THREAD

**Issue by InSuperposition** [ngrunwald/datasplash#73]
I'm just trying out a few of the examples seem outdated and/or buggy. 

In the current [PubSub example](https://github.com/ngrunwald/datasplash/blob/a5e6a36714ef7b8c6b7350e62111abcf45f6f721/src/clj/datasplash/examples.clj#L285-L330), I see a few issues
- `DataflowPipelineRunner` should be [`DataflowRunner` or `dataflow`](https://beam.apache.org/documentation/runners/dataflow/)
- `PubSubOptions`, when passed to `ds/make-pipeline` (`PubSubOptions` is unused in example currently), throws:
`
Property [project] is marked with contradictory annotations. Found [[Default.String(value=project-name-example) on PubSubOptions#getProject()], [Default.InstanceFactory(value=class org.apache.beam.sdk.extensions.gcp.options.GcpOptions$DefaultProjectFactory) on org.apache.beam.runners.dataflow.options.DataflowPipelineOptions#getProject()], [Default.InstanceFactory(value=class org.apache.beam.sdk.extensions.gcp.options.GcpOptions$DefaultProjectFactory) on org.apache.beam.sdk.extensions.gcp.options.GcpOptions#getProject()]].
`
- `project` value is `null` when calling from command-line and passing the argument correctly: `Syntax error (IllegalArgumentException) compiling at (/private/var/folders/y6/vb53_tq92019mpdmwkjdff600000gn/T/form-init9184696066443347895.clj:1:125).
Illegal project name specified in Pubsub subscription: null`

Path to README example's input file has been updated:
https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/WordCount.java#L162

**Comment by ngrunwald** [comment]
Done with release 0.6.5
