### ISSUE TITLE
Update Apache Beam SDK

### ISSUE THREAD

**Issue by InSuperposition** [ngrunwald/datasplash#76]
GCP Dataflow console suggests updating the Beam SDK

<img width="505" alt="dataflow0core-fgalloway-0724224641-fb83dfa6_Dataflow_-_Vindicia_-_Google_Cloud_Platform" src="https://user-images.githubusercontent.com/433871/62641210-0235ef00-b8f8-11e9-9d3d-b506c4ac2068.png">

**Comment by InSuperposition** [comment]
It appears Beam 2.1.4.0 has been released.
https://beam.apache.org/get-started/downloads/#releases

**Comment by RolT** [comment]
Hello,
This is done in the `devel` branch and is awaiting for release (df0f102a53b02533c4b035c3bcdbd6bfc277ab75, 4a45938fd03e435493f3dd1eb8665c8ea72b3072)

**Comment by bfontaine** [comment]
I merged on `master` but we need @ngrunwald for the deployment for now.

**Comment by ngrunwald** [comment]
Done with version 0.6.5
