### ISSUE TITLE
0.6.5 won't run on Java 8 anymore

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#82]
Hi there,

I'm getting the following when trying to use 0.6.5 on Java 8:

```
Execution error (UnsupportedClassVersionError) at java.lang.ClassLoader/defineClass1 (ClassLoader.java:-2).
datasplash/fns/ClojureDoFn has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Was the new version compiled with Java 11?

**Comment by domparry** [comment]
Just an update, I have confirmed that it runs with a version I compiled and published with Java 8. You can test with `[za.co.simply/datasplash "0.6.6"]`

**Comment by ngrunwald** [comment]
It's done with version 0.6.6, sorry for the delay. Should also have fixed cljdocs!
