### ISSUE TITLE
Templates / ValueProvider NullPointerException

### ISSUE THREAD

**Issue by xfthhxk** [ngrunwald/datasplash#84]
Hi I've been able to become productive with this library and love its Clojuery API.  I was hoping to create a template to work with Cloud Dataflow, however Beam requires using `ValueProvider`  getter/setters for the `PipelineOptions` interface.  

I get a NullPointerException when using `ValueProvider` as the type in `defoptions`.  Has anyone attempted this or perhaps there is an example to reference? Things work fine if the type is `String`.

Thanks!

```
(defoptions DataFetchOptions
  {
   :dataset       {:type        org.apache.beam.sdk.options.ValueProvider
                   :description "dataset"}})

(defn pipeline
  [args]
  (let [p    (ds/make-pipeline DataFetchOptions args)
        opts (ds/get-pipeline-options p)]
,,,,))
```

Error
```
java.lang.NullPointerException
PipelineOptionsFactory.java: 1637  org.apache.beam.sdk.options.PipelineOptionsFactory/isCollectionOrArrayOfAllowedTypes
PipelineOptionsFactory.java: 1573  org.apache.beam.sdk.options.PipelineOptionsFactory/parseObjects
PipelineOptionsFactory.java:  111  org.apache.beam.sdk.options.PipelineOptionsFactory/access$400
PipelineOptionsFactory.java:  294  org.apache.beam.sdk.options.PipelineOptionsFactory$Builder/as
                  core.clj:  974  datasplash.core/make-pipeline*
                  core.clj:  955  datasplash.core/make-pipeline*
                  core.clj:  984  datasplash.core/make-pipeline*
                  core.clj:  955  datasplash.core/make-pipeline*
```

**Comment by nbenketaf** [comment]
Hi @xfthhxk , are you still having the issue ?

I'm also trying to create a template. However, I don't get a NullPointerException, everything seems to be fine for me, except when I trigger the job, the template is ignoring the values I provide at runtime, but it uses the default values set for my `Options` type.

Anyone has been able to get the `ValueProvider` work with datasplash ?

Thanks.
Nabil

**Comment by xfthhxk** [comment]
@nbenketaf I haven't been able to figure this out.  Sorry :(

**Comment by nbenketaf** [comment]
@xfthhxk thanks for your reply.

Poke @ngrunwald ;)

**Comment by edporras** [comment]
@xfthhxk hi, wondering if this is still an open issue?

**Comment by xfthhxk** [comment]
Hi @edporras! I've not tried templates since 2019, though it will be something I look at again in the next couple of weeks for work.  I leave it to you if you'd like to close it.  I can always reopen if needed. Thanks.

**Comment by xfthhxk** [comment]
I'm closing this.  `ValueProvider` seems to be related to the classic (legacy?) templates.  The new flex templates don't use this. I've not tried the new flex templates and not sure if I will.
