### ISSUE TITLE
Different behavior of output for DataflowRunner vs. DirectRunner

### ISSUE THREAD

**Issue by sparkofreason** [ngrunwald/datasplash#85]
Not sure if this is an issue with datasplash or Beam, but web search isn't revealing anything. I'm seeing different behavior for output when I run locally via DirectRunner vs. on Dataflow when using sliding windows. All works as expected on Dataflow, but locally, there is not out, either with `ds/write-edn-file` or `ps/write-to-pubsub`. Input in this case is via `ps/read-from-pubsub`. If I just run locally from a bounded input soure, it works as expected locally. No errors that I can see, have tried looking through logs with DEBUG enabled and enabled the java default thread exception handler. The pipeline functions are being called

I'm hoping there's something obvious I'm overlooking here. My current code is kind of a mess, if an example is needed I'll try to put together a simple repro.

One hint: I'm using `ds/combine` with the definition below. When things work, `:extract` and `:combine` get called, not so in the non-working case.

```clojure
(defn map-stats
  [ks]
  (ds/combine-fn
   {:reduce (fn [acc v]
              (merge-with reduce-stats acc (select-keys v ks)))
    :extract (fn [acc]
               (println "EXTRACT")
               (reduce (fn [x [k v]] (assoc x k (extract-stats v))) {} acc))
    :combine (fn [& args] (println "COMBINE") (combine-stats-by-keys ks args))
    :init (constantly (->> ks
                           (map (fn [k] [k [0 0 Long/MAX_VALUE Long/MIN_VALUE 0]]))
                           (into {})))}))
```

**Comment by RolT** [comment]
Hello, what settings do you use when creating the pipeline, and how do you run/stop it ?

**Comment by sparkofreason** [comment]
Here are the options:

```clojure
(defoptions MyOptions
  {:input {:default "test_data.json"
           :type String}
   :output {:default "out.txt" #_"gs://my-bucket/out.txt"
            :type String}
   :numShards {:default 1
                :type Long}
   :pubsubProject {:default "my-project"
                   :type String}})
```

Here is `-main`:

```clojure
(defn -main
  [& args]
  (compile 'dave-dixon.dataflow)
  (let [p (ds/make-pipeline MyOptions args)
        {:keys [input output numShards]} (ds/get-pipeline-options p)]
    (->> p
         #_(ds/read-json-file input {:key-fn true})
         (ps/read-from-pubsub "projects/my-project/subscriptions/my-input-topic" {:type :raw :name "process_messages"})
         (ps/decode-messages {})
         (ds/map :payload)
         (queries)
         #_(ds/write-edn-file output {:num-shards 1 :name :write})
         (ps/write-to-pubsub "projects/my-project/topics/my-output-topic")
         (ds/run-pipeline))))
```

I run it from the REPL (socket REPL, via chlorine in atom, if that makes any difference). 

```clojure
  (in-ns 'dave-dixon.dataflow)
  (set-default-exception-handler!)
  (compile 'dave-dixon.dataflow)

  (-main "--runner=DirectRunner")

  (-main "--runner=DataflowRunner" "--project=my-project")
```

The first call to `-main` is for running locally, the second in Dataflow. These are executed manually, either/or, not at the same time.

**Comment by RolT** [comment]
Can you try `(-main "--runner=DirectRunner" "--streaming=true")` ?

**Comment by sparkofreason** [comment]
Same result. I also tried adding `{:streaming true}` to `ds/make-pipeline`, same thing.

Here is what is returned from `ds/get-pipeline-options

```clojure
{:numShards 1,
 :jobName "dave0dixon0dataflow-dave0dixon-0109163636-5d775468",
 :pubsubProject "my-project",
 :output "out.txt",
 :tempLocation nil,
 :userAgent "Apache_Beam_SDK_for_Java/2.15.0",
 :runner org.apache.beam.runners.direct.DirectRunner,
 :input "test_data.json",
 :stableUniqueNames
 #object[org.apache.beam.sdk.options.PipelineOptions$CheckEnabled 0x12b09318 "WARNING"],
 :optionsId 0}
```

**Comment by RolT** [comment]
Streaming is not appearing...
I did managed to run a streaming pipeline with the direct runner at some point, but I was using `'org.apache.beam.sdk.io.gcp.pubsub.PubsubOptions` (to connect to a local pubsub emulator). I don't know how to make it work with the `defoptions` macro. The way I see it is that we need to parameterize the interface extended by `defoptions`.

Could you try the following ?

```clojure
(do
 (clojure.core/gen-interface
  :name
  MyOptions
  :extends
  [org.apache.beam.sdk.options.StreamingOptions]
  :methods
  [[getInput [] String]
   [setInput [String] void]
   [getOutput [] String]
   [setOutput [String] void]
   [getNumShards [] Long]
   [setNumShards [Long] void]
   [getPubsubProject [] String]
   [setPubsubProject [String] void]])
 (def MyOptions 'MyOptions))
```

**Comment by RolT** [comment]
Or just doing `(ds/make-pipeline 'org.apache.beam.sdk.options.StreamingOptions args)` and setting `input output numShards` differently

**Comment by sparkofreason** [comment]
Tried both, same results, though it does show `:streaming true` in the options in both cases. But that gives me a place to start hacking, and if you think of anything else I'll give it a try. Thanks!

**Comment by sparkofreason** [comment]
Just to be sure, I did `(pprint (some-> p (.getPipelineOptions) (.isStreaming)))`, which gave `true`.

**Comment by RolT** [comment]
Ok, maybe try with `'org.apache.beam.sdk.io.gcp.pubsub.PubsubOptions`. I know it worked at some point (at least for datasplash 0.6.4), and i was using both windows and combine, with pubsub input and pubsub output

**Comment by sparkofreason** [comment]
Is there example code or tests for setting a trigger? Saw this, thought it might be worth a try.

https://stackoverflow.com/questions/54841814/directrunner-does-not-read-from-pub-sub-the-way-i-specified-with-fixedwindows-in

**Comment by sparkofreason** [comment]
`'org.apache.beam.sdk.io.gcp.pubsub.PubsubOptions` didn't make any difference.

**Comment by RolT** [comment]
I did have triggers. I guess you would be using Trigger$OnceTrigger and AfterPane here instead.

```clojure
(ns panoptes-streaming.triggers
  (:import [org.apache.beam.sdk.transforms.windowing AfterProcessingTime Repeatedly]
           [org.joda.time Duration]))

(defn mk-clock-trigger
  "Trigger that fires every t seconds"
  [t]
  (-> (AfterProcessingTime/pastFirstElementInPane)
      (.plusDelayOf (Duration/standardSeconds t))
      (Repeatedly/forever)))
```

```
(ns panoptes-streaming.pipeline
  (:require [datasplash.api :as ds]
            [clj-time.core :as time]
            [panoptes-streaming.triggers :as triggers])
  (:import (org.joda.time Duration)))

...
(ds/sliding-windows (time/millis window-len) (time/millis window-step)
                    {:trigger (triggers/mk-clock-trigger (time/in-seconds (time/millis refresh)))
                     :with-allowed-lateness Duration/ZERO
                     :accumulate-mode :accumulate
                     :name "sliding-window-rate-limit"} p)
...
```

**Comment by sparkofreason** [comment]
Your window definition made it work correctly. I tried the following (which I believe is the default), and it did not work:

```clojure
(ds/sliding-windows (time/seconds 60) (time/seconds 5)
                              {:trigger (AfterWatermark/pastEndOfWindow)
                               :with-allowed-lateness Duration/ZERO
                               :accumulate-mode :discard
                               :name "sliding-window-rate-limit"})
```

Maybe this is just a problem with DirectRunner, not something specific to datasplash? Anyway, what you sent gets me unstuck, many thanks.

**Comment by sparkofreason** [comment]
Options defined via `defoptions` works now with the trigger and the `--streaming=true` option.
