### ISSUE TITLE
Separate out non-core APIs from api.clj

### ISSUE THREAD

**Issue by timclemons** [ngrunwald/datasplash#94]
I'd like to propose restructuring the api resource so that optional dependencies such as bq and pubsub not be included in api.clj.  That would allow those of us not using those subsystems from having to pull in those dependencies while still having access to the syntactic sugar offered there.

Alternatively, include the syntactic sugar directly in core.clj.

**Comment by edporras** [comment]
This seems like a reasonable request to me. @ngrunwald thoughts?
